### ISSUE TITLE
Full github action example

### ISSUE THREAD

**Issue by nitrocode** [suzuki-shunsuke/tfprovidercheck#20]
It would be nice to have an out of the box action to run this tool.

Something like this

```yaml
name: Lint
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  tflint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout source code

    # Maybe an out of the box gha or a custom run and install
    # downloads https://github.com/suzuki-shunsuke/tfprovidercheck/releases/download/v0.2.0/tfprovidercheck_linux_amd64.tar.gz and installs it
    - uses: suzuki-shunsuke/tfprovidercheck 
      name: Setup tfprovidercheck
      with:
        version: v0.2.0

    - name: Show version
      run: tfprovidercheck --version

    - run: terraform version -json | tfprovidercheck
      env:
        TFPROVIDERCHECK_CONFIG_BODY: |
          providers:
            - name: registry.terraform.io/hashicorp/aws
              version: ">= 3.0.0"
```

Thanks for a nifty tool!
